/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclinica;

import java.util.logging.Level;
import java.util.logging.Logger;
import static proyectoclinica.FormPrincipal.PanelPrincipal;

/**
 *
 * @author Javier Rivera
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abrirATA = new javax.swing.JButton();
        abrirExpediente = new javax.swing.JButton();
        abrirConsultas = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema Clinica Unicah");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("¿Qué desea hacer?");

        abrirATA.setBackground(new java.awt.Color(255, 255, 204));
        abrirATA.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        abrirATA.setText("Ingresar un paciente al ATA");
        abrirATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirATAActionPerformed(evt);
            }
        });

        abrirExpediente.setBackground(new java.awt.Color(255, 255, 204));
        abrirExpediente.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        abrirExpediente.setText("Ingresar un nuevo expediente");
        abrirExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirExpedienteActionPerformed(evt);
            }
        });

        abrirConsultas.setBackground(new java.awt.Color(255, 255, 204));
        abrirConsultas.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        abrirConsultas.setText("Busqueda de información");
        abrirConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(abrirExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abrirATA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(abrirConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(abrirATA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abrirExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(abrirConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void abrirATAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirATAActionPerformed
        // TODO add your handling code here:
        IngresoATA ata;
        try {
            ata = new IngresoATA();
            ata.setSize(1380, 730);
            PanelPrincipal.removeAll();
            PanelPrincipal.add(ata);
            PanelPrincipal.revalidate();
            PanelPrincipal.repaint();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirATAActionPerformed

    private void abrirExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirExpedienteActionPerformed
        // TODO add your handling code here:
        IngresoExpediente expediente = new IngresoExpediente();
        expediente.setSize(1380, 730);
        
        PanelPrincipal.removeAll();
        PanelPrincipal.add(expediente);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_abrirExpedienteActionPerformed

    private void abrirConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirConsultasActionPerformed
        // TODO add your handling code here:
        PanelConsultas pc = new PanelConsultas();
        pc.setSize(1380, 730);
        
        PanelPrincipal.removeAll();
        PanelPrincipal.add(pc);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_abrirConsultasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirATA;
    private javax.swing.JButton abrirConsultas;
    private javax.swing.JButton abrirExpediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
